package_upgrade: true

ssh_deletekeys: true
ssh_pwauth: false

packages:
  - lib32stdc++6
  - expect

disable_root: true

users:
  - default
  - name: steam
    gecos: Steam / Source User

write_files:
  - path: /etc/systemd/system/css.service
    content: |
      [Unit]
      Description=Counter-Strike Source Service.
      After=network-online.target

      [Service]
      Type=simple
      ExecStartPre=cloud-init status --long --wait
      ExecStart=\
        /opt/css/srcds_run \
        -game cstrike \
        -console \
        -usercon \
        -steam \
        -port 27015 \
        -steam_dir /opt/steamcmd \
        -steamcmd_script /opt/css/updatescript \
        +sv_lan 0 \
        +map de_dust2 \
        +maxplayers 9
      User=steam
      Group=steam
      StandardOutput=journal+console
      StandardError=journal+console
      PermissionsStartOnly=false
      RestartSec=30s
      Restart=always

      [Install]
      WantedBy=multi-user.target
    permissions: '0644'

