package_upgrade: true

ssh_deletekeys: false

packages:
  - lib32stdc++6
  - expect

users:
  - name: steam
    gecos: Steam / Source User

write_files:
  - path: /etc/systemd/system/css.service
    content: |
      [Unit]
      Description=Counter-Strike Source Service.

      [Service]
      Type=simple
      ExecStart=\
        /opt/css/srcds_run \
        -game cstrike \
        -console \
        -steam \
        -port 27015 \
        -steam_dir /opt/steam \
        -steamcmd_script /opt/css/updatescript \
        +sv_lan 0 \
        +map de_dust2 \
        +maxplayers 9
      User=steam
      Group=steam

      [Install]
      WantedBy=multi-user.target
    permissions: '0644'

